version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-{{ checksum "poetry.lock" }}
      - run:
          name: Install dependencies
          command: |
            poetry install
      - save_cache:
          key: deps-{{ checksum "poetry.lock" }}
          paths:
            - /home/circleci/.cache/pypoetry/virtualenvs
      - run:
          name: Run flake8
          command: |
            poetry run flake8 .
      - run:
          name: Run tests and coverage
          command: |
            poetry run coverage run --omit="/home/circleci/.cache/pypoetry/virtualenvs" -m pytest
  publish:
    executor: python/default
    steps:
      - checkout
      - run:
          name: Publish to PyPI
          command: |
            poetry publish --verbose --build --username "${PYPI_USERNAME}" --password "${PYPI_API_TOKEN}" --no-interaction
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-and-test
      - publish:
          requires:
            - build-and-test
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
