version: 2.1

orbs:
  python: circleci/python@1.3.2

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.8/dist-packages
      - restore_cache:
          keys:
            - deps-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Install dependencies
          command: |
            make install
      - save_cache:
          key: deps-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - /usr/local/bin
            - /usr/local/lib/python3.8/site-packages
      - run:
          name: Run flake8
          command: |
            make lint
      - run:
          name: Run tests and coverage
          command: |
            make tests
            make coverage
      - store_test_results:
            path: test-results.xml
  publish:
    executor: python/default
    steps:
      - checkout
      - run:
          name: Publish to PyPI
          environment:
              TWINE_USERNAME: __token__
              TWINE_PASSWORD: ${PYPI_API_TOKEN}
          command: |
            make publish
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-and-test:
          filters:
            tags:
              only: /^v.*/
      - publish:
          requires:
            - build-and-test
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
